import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { dependency } from './dependencies.mjs';
const JSZip = dependency('jszip');
const root = path.resolve(import.meta.dirname, '..');
const manifest = JSON.parse(await fs.readFile(path.join(root, 'extension/manifest.json')));
const pkg = JSON.parse(await fs.readFile(path.join(root, 'package.json')));
if (manifest.version !== pkg.version) throw new Error('Version mismatch');
const files = ['manifest.json', 'core.js', 'source.js', 'clean.js', 'view.js', 'app.js', 'options.html', 'options.css', 'options.js'];
const zip = new JSZip();
for (const file of files.sort()) zip.file(file, await fs.readFile(path.join(root, 'extension', file)), { date: new Date('2026-01-01T00:00:00Z'), unixPermissions: 0o100644 });
zip.file('LICENSE', await fs.readFile(path.join(root, 'LICENSE')), { date: new Date('2026-01-01T00:00:00Z'), unixPermissions: 0o100644 });
const bytes = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE', compressionOptions: { level: 9 }, platform: 'UNIX' });
await fs.mkdir(path.join(root, 'release'), { recursive: true });
const filename = `MailWeave-v${manifest.version}.zip`;
await fs.writeFile(path.join(root, 'release', filename), bytes);
await fs.writeFile(path.join(root, 'release', `${filename}.sha256`), `${crypto.createHash('sha256').update(bytes).digest('hex')}  ${filename}\n`);
console.log(`${filename}: ${bytes.length} bytes, runtime allowlist only`);
